# Site settings
email: andre@vollrath.ca
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: By Another Name
description: by Drew
url: "https://andrevollrath.github.io/"
twitter_username: 
default_img: 

# Profile settings
name: Drew Vollrath
profile_img: "/assets/FOUND3.jpg"
profile: Drew was born in North Vancouver, BC and then transported into the backwoods of BC for the rest of his life. Somehow he found a computer and is now on learn.co. Not sure how that happened.
social: 
  github: "https://github.com/andrevollrath/"
  instagram: "https://www.instagram.com/drew.vollrath/"
  heart: "https://learn.co/andrevollrath"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
