# Site settings
email: andre@vollrath.ca
baseurl: "https://andrevollrath.github.io/"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: By Another Name
description: by Drew
url: "https://andrevollrath.github.io/"
twitter_username: 
default_img: 

# Profile settings
name: Drew Vollrath
profile_img: 
profile: Drew was born in North Vancouver, BC. At the age of 8 he was transported 
kicking and screaming to the backwoods of BC. Since, he has dedicated his life to
being a super hero accountant but failed miserably. Not he is obsessed with learn.co!
social:
github: andrevollrath

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
